/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ReportBugRouteImport } from './routes/report-bug'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as PayOrderIdRouteImport } from './routes/pay.$orderId'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated.dashboard.admin'
import { Route as AuthenticatedDashboardApiKeysRouteImport } from './routes/_authenticated.dashboard.api-keys'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated.dashboard.billing'
import { Route as AuthenticatedDashboardSecurityRouteImport } from './routes/_authenticated.dashboard.security'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated.dashboard.settings'
import { Route as AuthenticatedDashboardTransactionsRouteImport } from './routes/_authenticated.dashboard.transactions'
import { Route as AuthenticatedDashboardWebhooksRouteImport } from './routes/_authenticated.dashboard.webhooks'
import { Route as ApiPaymentOrderIdRouteImport } from './routes/api/payment.$orderId'
import { Route as ApiPublicHooksVerifyRouteImport } from './routes/api/public/hooks/verify'
import { Route as ApiPublicPaymentOrderIdRouteImport } from './routes/api/public/payment.$orderId'
import { Route as ApiPublicV1CreateOrderRouteImport } from './routes/api/public/v1/create-order'
import { Route as ApiPublicV1CheckStatusOrderIdRouteImport } from './routes/api/public/v1/check-status.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportBugRoute = ReportBugRouteImport.update({
  id: '/report-bug',
  path: '/report-bug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PayOrderIdRoute = PayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardApiKeysRoute =
  AuthenticatedDashboardApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSecurityRoute =
  AuthenticatedDashboardSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTransactionsRoute =
  AuthenticatedDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWebhooksRoute =
  AuthenticatedDashboardWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPaymentOrderIdRoute = ApiPaymentOrderIdRouteImport.update({
  id: '/api/payment/$orderId',
  path: '/api/payment/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksVerifyRoute = ApiPublicHooksVerifyRouteImport.update({
  id: '/api/public/hooks/verify',
  path: '/api/public/hooks/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentOrderIdRoute = ApiPublicPaymentOrderIdRouteImport.update({
  id: '/api/public/payment/$orderId',
  path: '/api/public/payment/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CreateOrderRoute = ApiPublicV1CreateOrderRouteImport.update({
  id: '/api/public/v1/create-order',
  path: '/api/public/v1/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CheckStatusOrderIdRoute =
  ApiPublicV1CheckStatusOrderIdRouteImport.update({
    id: '/api/public/v1/check-status/$orderId',
    path: '/api/public/v1/check-status/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/report-bug': typeof ReportBugRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/pay/$orderId': typeof PayOrderIdRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/security': typeof AuthenticatedDashboardSecurityRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/api/payment/$orderId': typeof ApiPaymentOrderIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/verify': typeof ApiPublicHooksVerifyRoute
  '/api/public/payment/$orderId': typeof ApiPublicPaymentOrderIdRoute
  '/api/public/v1/create-order': typeof ApiPublicV1CreateOrderRoute
  '/api/public/v1/check-status/$orderId': typeof ApiPublicV1CheckStatusOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/report-bug': typeof ReportBugRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/security': typeof AuthenticatedDashboardSecurityRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/api/payment/$orderId': typeof ApiPaymentOrderIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/verify': typeof ApiPublicHooksVerifyRoute
  '/api/public/payment/$orderId': typeof ApiPublicPaymentOrderIdRoute
  '/api/public/v1/create-order': typeof ApiPublicV1CreateOrderRoute
  '/api/public/v1/check-status/$orderId': typeof ApiPublicV1CheckStatusOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/report-bug': typeof ReportBugRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/pay/$orderId': typeof PayOrderIdRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/security': typeof AuthenticatedDashboardSecurityRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/_authenticated/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/api/payment/$orderId': typeof ApiPaymentOrderIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/verify': typeof ApiPublicHooksVerifyRoute
  '/api/public/payment/$orderId': typeof ApiPublicPaymentOrderIdRoute
  '/api/public/v1/create-order': typeof ApiPublicV1CreateOrderRoute
  '/api/public/v1/check-status/$orderId': typeof ApiPublicV1CheckStatusOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/faq'
    | '/privacy'
    | '/refunds'
    | '/report-bug'
    | '/reset-password'
    | '/support'
    | '/terms'
    | '/dashboard'
    | '/pay/$orderId'
    | '/dashboard/admin'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/webhooks'
    | '/api/payment/$orderId'
    | '/dashboard/'
    | '/api/public/hooks/verify'
    | '/api/public/payment/$orderId'
    | '/api/public/v1/create-order'
    | '/api/public/v1/check-status/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/faq'
    | '/privacy'
    | '/refunds'
    | '/report-bug'
    | '/reset-password'
    | '/support'
    | '/terms'
    | '/pay/$orderId'
    | '/dashboard/admin'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/webhooks'
    | '/api/payment/$orderId'
    | '/dashboard'
    | '/api/public/hooks/verify'
    | '/api/public/payment/$orderId'
    | '/api/public/v1/create-order'
    | '/api/public/v1/check-status/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/faq'
    | '/privacy'
    | '/refunds'
    | '/report-bug'
    | '/reset-password'
    | '/support'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/pay/$orderId'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/api-keys'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/security'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/transactions'
    | '/_authenticated/dashboard/webhooks'
    | '/api/payment/$orderId'
    | '/_authenticated/dashboard/'
    | '/api/public/hooks/verify'
    | '/api/public/payment/$orderId'
    | '/api/public/v1/create-order'
    | '/api/public/v1/check-status/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ReportBugRoute: typeof ReportBugRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  PayOrderIdRoute: typeof PayOrderIdRoute
  ApiPaymentOrderIdRoute: typeof ApiPaymentOrderIdRoute
  ApiPublicHooksVerifyRoute: typeof ApiPublicHooksVerifyRoute
  ApiPublicPaymentOrderIdRoute: typeof ApiPublicPaymentOrderIdRoute
  ApiPublicV1CreateOrderRoute: typeof ApiPublicV1CreateOrderRoute
  ApiPublicV1CheckStatusOrderIdRoute: typeof ApiPublicV1CheckStatusOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-bug': {
      id: '/report-bug'
      path: '/report-bug'
      fullPath: '/report-bug'
      preLoaderRoute: typeof ReportBugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/pay/$orderId': {
      id: '/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/pay/$orderId'
      preLoaderRoute: typeof PayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/api-keys': {
      id: '/_authenticated/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof AuthenticatedDashboardApiKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/security': {
      id: '/_authenticated/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof AuthenticatedDashboardSecurityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/transactions': {
      id: '/_authenticated/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/webhooks': {
      id: '/_authenticated/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof AuthenticatedDashboardWebhooksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/payment/$orderId': {
      id: '/api/payment/$orderId'
      path: '/api/payment/$orderId'
      fullPath: '/api/payment/$orderId'
      preLoaderRoute: typeof ApiPaymentOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/verify': {
      id: '/api/public/hooks/verify'
      path: '/api/public/hooks/verify'
      fullPath: '/api/public/hooks/verify'
      preLoaderRoute: typeof ApiPublicHooksVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment/$orderId': {
      id: '/api/public/payment/$orderId'
      path: '/api/public/payment/$orderId'
      fullPath: '/api/public/payment/$orderId'
      preLoaderRoute: typeof ApiPublicPaymentOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/create-order': {
      id: '/api/public/v1/create-order'
      path: '/api/public/v1/create-order'
      fullPath: '/api/public/v1/create-order'
      preLoaderRoute: typeof ApiPublicV1CreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/check-status/$orderId': {
      id: '/api/public/v1/check-status/$orderId'
      path: '/api/public/v1/check-status/$orderId'
      fullPath: '/api/public/v1/check-status/$orderId'
      preLoaderRoute: typeof ApiPublicV1CheckStatusOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardApiKeysRoute: typeof AuthenticatedDashboardApiKeysRoute
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardSecurityRoute: typeof AuthenticatedDashboardSecurityRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardTransactionsRoute: typeof AuthenticatedDashboardTransactionsRoute
  AuthenticatedDashboardWebhooksRoute: typeof AuthenticatedDashboardWebhooksRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardApiKeysRoute: AuthenticatedDashboardApiKeysRoute,
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardSecurityRoute: AuthenticatedDashboardSecurityRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardTransactionsRoute:
      AuthenticatedDashboardTransactionsRoute,
    AuthenticatedDashboardWebhooksRoute: AuthenticatedDashboardWebhooksRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ReportBugRoute: ReportBugRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  PayOrderIdRoute: PayOrderIdRoute,
  ApiPaymentOrderIdRoute: ApiPaymentOrderIdRoute,
  ApiPublicHooksVerifyRoute: ApiPublicHooksVerifyRoute,
  ApiPublicPaymentOrderIdRoute: ApiPublicPaymentOrderIdRoute,
  ApiPublicV1CreateOrderRoute: ApiPublicV1CreateOrderRoute,
  ApiPublicV1CheckStatusOrderIdRoute: ApiPublicV1CheckStatusOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
